tasks:
  - name: Instalar Python
    init: > 
      pyenv install 3.10.7 -f &&
      pyenv local 3.10.7 &&
      gp sync-done bundle
  - name: Instalar dependencias
    init: gp sync-await bundle
    command: pip install -r requirements.txt && pip install -r sidecar-requirements.txt && pip install -r ui-requirements.txt
  - name: Crear imagenes Docker
    init: > 
      docker build . -f propiedadDeLosAlpes.Dockerfile -t propiedadDeLosAlpes/flask &&
      docker build . -f adaptador.Dockerfile -t propiedadDeLosAlpes/adaptador &&
      gp sync-done images
  - name: Crear folder para datos y asigna permisos
    init: > 
      mkdir -p data/bookkeeper && 
      mkdir -p data/zookeeper && 
      sudo chmod -R 777 ./data
  - name: Pull el Docker compose
    init: gp sync-await images
    command: docker-compose pull
  - name: Instalar y configurar PostgreSQL
    init: > 
      sudo apt-get update &&
      sudo apt-get install -y postgresql postgresql-contrib &&
      sudo service postgresql start
#      sudo -u postgres psql -c "CREATE USER gitpod WITH PASSWORD 'gitpod';" &&
#      sudo -u postgres psql -c "CREATE DATABASE gitpod OWNER gitpod;" &&
#      gp sync-done postgresql
  - name: Configurar variables de entorno
    command: > 
      export DATABASE_URL=postgresql://gitpod:gitpod@localhost/gitpod
