# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: propiedades.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11propiedades.proto\x12\x0bpropiedades\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x02\n\tPropiedad\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bpropietario\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x37\n\x0e\x66\x65\x63ha_creacion\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x02\x88\x01\x01\x12<\n\x13\x66\x65\x63ha_actualizacion\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x03\x88\x01\x01\x12\x11\n\x04pais\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x1a\n\rtipoPropiedad\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x16\n\tdireccion\x18\x07 \x01(\tH\x06\x88\x01\x01\x42\x05\n\x03_idB\x0e\n\x0c_propietarioB\x11\n\x0f_fecha_creacionB\x16\n\x14_fecha_actualizacionB\x07\n\x05_paisB\x10\n\x0e_tipoPropiedadB\x0c\n\n_direccion\"c\n\x12RespuestaPropiedad\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12.\n\tpropiedad\x18\x02 \x01(\x0b\x32\x16.propiedades.PropiedadH\x00\x88\x01\x01\x42\x0c\n\n_propiedad2Z\n\x0bPropiedades\x12K\n\x0e\x43rearPropiedad\x12\x16.propiedades.Propiedad\x1a\x1f.propiedades.RespuestaPropiedad\"\x00\x42\x33\n\x18\x63o.edu.uniandes.misw4406B\x0ePropiedadProtoP\x01\xa2\x02\x04PROPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'propiedades_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030co.edu.uniandes.misw4406B\016PropiedadProtoP\001\242\002\004PROP'
  _PROPIEDAD._serialized_start=68
  _PROPIEDAD._serialized_end=419
  _RESPUESTAPROPIEDAD._serialized_start=421
  _RESPUESTAPROPIEDAD._serialized_end=520
  _PROPIEDADES._serialized_start=522
  _PROPIEDADES._serialized_end=612
# @@protoc_insertion_point(module_scope)
